server:
  port: 8333
spring:
  application:
    name: ishow-gateway
  cloud:
    gateway:
      discovery:
        locator:
        enabled: false
        lowerCaseServiceId: true
# 关闭权限验证
info:
  app:
    name: ishow-gateway
